### ISSUE TITLE
Services Gateway: show language runtime in table view

### ISSUE THREAD

**Issue by tilleryd** [DecipherNow/gm-fabric-dashboard#855] opened 2017-11-05 02:30 UTC

**Comment by tilleryd** [comment] 2017-11-05 02:31
@shanberg I don't know if it was intentional to leave out language runtime from the table view but I find it really useful on the card view.

**Comment by spmcbride1201** [comment] 2017-11-07 15:25
Duplicate of #888

**Closed by spmcbride1201** 2017-11-07 15:25 UTC
