### ISSUE TITLE
Group dropdown is overlaid with another element.

### ISSUE THREAD

**Issue by tilleryd** [DecipherNow/gm-fabric-dashboard#862] opened 2017-11-06 00:04 UTC
<img width="492" alt="screen shot 2017-11-05 at 7 02 49 pm" src="https://user-images.githubusercontent.com/2581080/32420684-268de2fc-c25c-11e7-9f81-b0feb3beb568.png">

**Comment by spmcbride1201** [comment] 2017-11-06 15:29
Closing because duplicate of #852

**Closed by spmcbride1201** 2017-11-06 15:29 UTC
Labels: bug
