### ISSUE TITLE
Instance view: the contents of the left/right readouts in Vitals are not vertically centered in Safari.

### ISSUE THREAD

**Issue by tilleryd** [DecipherNow/gm-fabric-dashboard#1007] opened 2017-11-15 22:00 UTC
## Expected Behavior
<img width="1920" alt="screen shot 2017-11-15 at 4 57 56 pm" src="https://user-images.githubusercontent.com/2581080/32862506-4ba759de-ca26-11e7-8c3a-dd53dca9fb64.png">

## Actual Behavior
![screen shot 2017-11-15 at 4 57 56 pm 2](https://user-images.githubusercontent.com/2581080/32862526-57b58ed0-ca26-11e7-9560-d43052fc850d.png)

## Specifications

  - Version: 0.9.1
  - Platform: macOS Sierra 10.12.4
  - Subsystem: Safari 10.1

**Comment by karinakeen** [comment] 2017-11-30 22:48
"In Safari 10.1 and below, the height of (non flex) children are not recognized in percentages. However other browsers recognize and scale the children based on percentage heights. Fixed in all versions > 10.1 (See bug) The bug also appeared in Chrome but was fixed in Chrome 51"
https://caniuse.com/#search=flex
https://github.com/philipwalton/flexbugs/issues/197

Looking for workaround...

**Comment by karinakeen** [comment] 2017-11-30 22:49
Confirmed the problem is gone in Safari 11 but still seeing in in 10.1

![screen shot 2017-11-30 at 5 01 46 pm](https://user-images.githubusercontent.com/26534838/33459107-c9ce50b6-d5f6-11e7-942a-45cca2269afb.png)

**Closed** 2017-12-04 15:06 UTC
Labels: bug, priority-2
